import React from 'react';
import { Link } from 'react-router-dom';
import logoSvg from '../assets/Logo.svg?url';
import {
  Linkedin,
  X,
  Youtube,
  Facebook
} from 'lucide-react';

export default function PrivacyPolicy() {
  return (
    <div className="min-h-screen bg-amber-50 text-amber-900 font-sans">
      <header className="bg-white border-b border-amber-200 py-6 px-6 shadow-sm">
        <div className="max-w-7xl mx-auto flex items-center justify-between gap-4">
          <div>
            <p className="text-sm uppercase tracking-[0.3em] text-amber-500">AgentsForgeX</p>
            <h1 className="text-3xl font-bold text-amber-900">Privacy Policy</h1>
          </div>
          <Link
            to="/"
            className="inline-flex items-center justify-center rounded-full border border-amber-700 bg-amber-100 px-4 py-2 text-sm font-semibold text-amber-900 hover:bg-amber-200 transition">
            Home
          </Link>
        </div>
      </header>

      <main className="max-w-5xl mx-auto px-6 py-12 space-y-8">
        <section className="space-y-4">
          <h1 className="text-4xl font-bold text-amber-900">Privacy Policy</h1>
          <p className="text-sm text-amber-700">Last updated: June 24, 2026</p>
          <p className="text-amber-800 leading-relaxed">
            This Privacy Policy describes Our policies and procedures on the collection, use and disclosure of Your information when You use the Service and tells You about Your privacy rights and how the law protects You.
          </p>
          <p className="text-amber-800 leading-relaxed">
            We use Your Personal Data to provide and improve the Service. By using the Service, You agree to the collection and use of information in accordance with this Privacy Policy.
          </p>
        </section>

        <section className="space-y-4">
          <h2 className="text-3xl font-bold text-amber-900">Interpretation and Definitions</h2>
          <h3 className="text-2xl font-semibold text-amber-900">Interpretation</h3>
          <p className="text-amber-800 leading-relaxed">
            The words whose initial letters are capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or in plural.
          </p>
          <h3 className="text-2xl font-semibold text-amber-900">Definitions</h3>
          <p className="text-amber-800 leading-relaxed">For the purposes of this Privacy Policy:</p>
          <ul className="list-disc space-y-3 pl-6 text-amber-800">
            <li>
              <strong>Account</strong> means a unique account created for You to access our Service or parts of our Service.
            </li>
            <li>
              <strong>Affiliate</strong> means an entity that controls, is controlled by, or is under common control with a party, where "control" means ownership of 50% or more of the shares, equity interest or other securities entitled to vote for election of directors or other managing authority.
            </li>
            <li>
              <strong>Company</strong> (referred to as either "the Company", "We", "Us" or "Our" in this Privacy Policy) refers to Agentsforgex, 1455 Market St, San Francisco, CA 94103, USA.
            </li>
            <li>
              <strong>Cookies</strong> are small files that are placed on Your computer, mobile device or any other device by a website, containing the details of Your browsing history on that website among its many uses.
            </li>
            <li>
              <strong>Country</strong> refers to: California, United States.
            </li>
            <li>
              <strong>Device</strong> means any device that can access the Service such as a computer, a cell phone or a digital tablet.
            </li>
            <li>
              <strong>Personal Data</strong> (or "Personal Information") is any information that relates to an identified or identifiable individual.
            </li>
            <li>
              <strong>Service</strong> refers to the Website.
            </li>
            <li>
              <strong>Service Provider</strong> means any natural or legal person who processes the data on behalf of the Company.
            </li>
            <li>
              <strong>Usage Data</strong> refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit).
            </li>
            <li>
              <strong>Website</strong> refers to agentsforgex, accessible from{' '}
              <a
                href="https://agentsforgex.com/"
                rel="external nofollow noopener"
                target="_blank"
                className="text-amber-900 underline hover:text-amber-700">
                https://agentsforgex.com/
              </a>
            </li>
            <li>
              <strong>You</strong> means the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable.
            </li>
          </ul>
        </section>

        <section className="space-y-4">
          <h2 className="text-3xl font-bold text-amber-900">Collecting and Using Your Personal Data</h2>
          <h3 className="text-2xl font-semibold text-amber-900">Types of Data Collected</h3>
          <h4 className="text-xl font-semibold text-amber-900">Personal Data</h4>
          <p className="text-amber-800 leading-relaxed">
            While using Our Service, We may ask You to provide Us with certain personally identifiable information that can be used to contact or identify You. Personally identifiable information may include, but is not limited to:
          </p>
          <ul className="list-disc space-y-2 pl-6 text-amber-800">
            <li>Email address</li>
            <li>First name and last name</li>
          </ul>

          <h4 className="text-xl font-semibold text-amber-900">Usage Data</h4>
          <p className="text-amber-800 leading-relaxed">Usage Data is collected automatically when using the Service.</p>
          <p className="text-amber-800 leading-relaxed">
            Usage Data may include information such as Your Device's Internet Protocol address (e.g. IP address), browser type, browser version, the pages of our Service that You visit, the time and date of Your visit, the time spent on those pages, unique device identifiers and other diagnostic data.
          </p>
          <p className="text-amber-800 leading-relaxed">
            When You access the Service by or through a mobile device, We may collect certain information automatically, including, but not limited to, the type of mobile device You use, Your mobile device's unique ID, the IP address of Your mobile device, Your mobile operating system, the type of mobile Internet browser You use, unique device identifiers and other diagnostic data.
          </p>
          <p className="text-amber-800 leading-relaxed">
            We may also collect information that Your browser sends whenever You visit Our Service or when You access the Service by or through a mobile device.
          </p>

          <h4 className="text-xl font-semibold text-amber-900">Tracking Technologies and Cookies</h4>
          <p className="text-amber-800 leading-relaxed">
            We use Cookies and similar tracking technologies to track the activity on Our Service and store certain information. Tracking technologies We use include beacons, tags, and scripts to collect and track information and to improve and analyze Our Service. The technologies We use may include:
          </p>
          <ul className="list-disc space-y-2 pl-6 text-amber-800">
            <li>
              <strong>Cookies or Browser Cookies.</strong> A cookie is a small file placed on Your Device. You can instruct Your browser to refuse all Cookies or to indicate when a Cookie is being sent. However, if You do not accept Cookies, You may not be able to use some parts of our Service.
            </li>
            <li>
              <strong>Web Beacons.</strong> Certain sections of our Service and our emails may contain small electronic files known as web beacons (also referred to as clear gifs, pixel tags, and single-pixel gifs) that permit the Company, for example, to count users who have visited those pages or opened an email and for other related website statistics.
            </li>
          </ul>
          <p className="text-amber-800 leading-relaxed">
            Cookies can be "Persistent" or "Session" Cookies. Persistent Cookies remain on Your personal computer or mobile device when You go offline, while Session Cookies are deleted as soon as You close Your web browser.
          </p>
          <p className="text-amber-800 leading-relaxed">
            Where required by law, we use non-essential cookies (such as analytics, advertising, and remarketing cookies) only with Your consent. You can withdraw or change Your consent at any time using Our cookie preferences tool (if available) or through Your browser/device settings. Withdrawing consent does not affect the lawfulness of processing based on consent before its withdrawal.
          </p>
          <p className="text-amber-800 leading-relaxed">
            We use both Session and Persistent Cookies for the purposes set out below:
          </p>
          <ul className="list-disc space-y-2 pl-6 text-amber-800">
            <li>
              <strong>Necessary / Essential Cookies</strong>
              <p className="mt-1 text-amber-800">Type: Session Cookies</p>
              <p className="text-amber-800">Administered by: Us</p>
              <p className="text-amber-800">Purpose: These Cookies are essential to provide You with services available through the Website and to enable You to use some of its features...</p>
            </li>
            <li>
              <strong>Cookies Policy / Notice Acceptance Cookies</strong>
              <p className="mt-1 text-amber-800">Type: Persistent Cookies</p>
              <p className="text-amber-800">Administered by: Us</p>
              <p className="text-amber-800">Purpose: These Cookies identify if users have accepted the use of cookies on the Website.</p>
            </li>
            <li>
              <strong>Functionality Cookies</strong>
              <p className="mt-1 text-amber-800">Type: Persistent Cookies</p>
              <p className="text-amber-800">Administered by: Us</p>
              <p className="text-amber-800">Purpose: These Cookies allow Us to remember choices You make when You use the Website...</p>
            </li>
          </ul>
        </section>

        <section className="space-y-4">
          <h3 className="text-2xl font-semibold text-amber-900">Use of Your Personal Data</h3>
          <p className="text-amber-800 leading-relaxed">The Company may use Personal Data for the following purposes:</p>
          <ul className="list-disc space-y-3 pl-6 text-amber-800">
            <li>
              <strong>To provide and maintain our Service</strong>, including to monitor the usage of our Service.
            </li>
            <li>
              <strong>To manage Your Account:</strong> to manage Your registration as a user of the Service...
            </li>
            <li>
              <strong>For the performance of a contract:</strong> the development, compliance and undertaking of the purchase contract...
            </li>
            <li>
              <strong>To contact You:</strong> To contact You by email, telephone calls, SMS, or other equivalent forms...
            </li>
            <li>
              <strong>To provide You</strong> with news, special offers, and general information about other goods, services and events...
            </li>
            <li>
              <strong>To manage Your requests:</strong> To attend and manage Your requests to Us.
            </li>
            <li>
              <strong>For business transfers:</strong> We may use Your Personal Data to evaluate or conduct a merger...</li>
            <li>
              <strong>For other purposes</strong>: We may use Your information for other purposes, such as data analysis...</li>
          </ul>
          <p className="text-amber-800 leading-relaxed">We may share Your Personal Data in the following situations:</p>
          <ul className="list-disc space-y-2 pl-6 text-amber-800">
            <li><strong>With Service Providers:</strong> We may share Your Personal Data with Service Providers to monitor and analyze the use of our Service, to contact You.</li>
            <li><strong>For business transfers:</strong> We may share or transfer Your Personal Data in connection with, or during negotiations of, any merger...</li>
            <li><strong>With Affiliates:</strong> We may share Your Personal Data with Our affiliates...</li>
            <li><strong>With business partners:</strong> We may share Your Personal Data with Our business partners...</li>
            <li><strong>With other users:</strong> If Our Service offers public areas, when You share Personal Data or otherwise interact in the public areas...</li>
            <li><strong>With Your consent</strong>: We may disclose Your Personal Data for any other purpose with Your consent.</li>
          </ul>
        </section>

        <section className="space-y-4">
          <h3 className="text-2xl font-semibold text-amber-900">Retention of Your Personal Data</h3>
          <p className="text-amber-800 leading-relaxed">The Company will retain Your Personal Data only for as long as is necessary for the purposes set out in this Privacy Policy...</p>
          <ul className="list-disc space-y-3 pl-6 text-amber-800">
            <li>
              <strong>Account Information</strong>
              <ul className="list-disc pl-6 space-y-2">
                <li>User Accounts: retained for the duration of your account relationship plus up to 24 months after account closure...</li>
              </ul>
            </li>
            <li>
              <strong>Customer Support Data</strong>
              <ul className="list-disc pl-6 space-y-2">
                <li>Support tickets and correspondence: up to 24 months from the date of ticket closure...</li>
                <li>Chat transcripts: up to 24 months for quality assurance and staff training purposes.</li>
              </ul>
            </li>
            <li>
              <strong>Usage Data</strong>
              <ul className="list-disc pl-6 space-y-2">
                <li>Website analytics data (cookies, IP addresses, device identifiers): up to 24 months from the date of collection...</li>
                <li>Server logs (IP addresses, access times): up to 24 months for security monitoring and troubleshooting purposes.</li>
              </ul>
            </li>
          </ul>
          <p className="text-amber-800 leading-relaxed">Usage Data is retained in accordance with the retention periods described above...</p>
        </section>

        <section className="space-y-4">
          <h3 className="text-2xl font-semibold text-amber-900">Transfer of Your Personal Data</h3>
          <p className="text-amber-800 leading-relaxed">Your information, including Personal Data, is processed at the Company's operating offices and in any other places where the parties involved in the processing are located.</p>
          <p className="text-amber-800 leading-relaxed">Where required by applicable law, We will ensure that international transfers of Your Personal Data are subject to appropriate safeguards and supplementary measures where appropriate.</p>
        </section>

        <section className="space-y-4">
          <h3 className="text-2xl font-semibold text-amber-900">Delete Your Personal Data</h3>
          <p className="text-amber-800 leading-relaxed">You have the right to delete or request that We assist in deleting the Personal Data that We have collected about You.</p>
          <p className="text-amber-800 leading-relaxed">Our Service may give You the ability to delete certain information about You from within the Service.</p>
          <p className="text-amber-800 leading-relaxed">You may update, amend, or delete Your information at any time by signing in to Your Account...</p>
          <p className="text-amber-800 leading-relaxed">Please note, however, that We may need to retain certain information when we have a legal obligation or lawful basis to do so.</p>
        </section>

        <section className="space-y-4">
          <h3 className="text-2xl font-semibold text-amber-900">Disclosure of Your Personal Data</h3>
          <h4 className="text-xl font-semibold text-amber-900">Business Transactions</h4>
          <p className="text-amber-800 leading-relaxed">If the Company is involved in a merger, acquisition or asset sale, Your Personal Data may be transferred...</p>
          <h4 className="text-xl font-semibold text-amber-900">Law enforcement</h4>
          <p className="text-amber-800 leading-relaxed">Under certain circumstances, the Company may be required to disclose Your Personal Data if required to do so by law...</p>
          <h4 className="text-xl font-semibold text-amber-900">Other legal requirements</h4>
          <p className="text-amber-800 leading-relaxed">The Company may disclose Your Personal Data in the good faith belief that such action is necessary to:</p>
          <ul className="list-disc space-y-2 pl-6 text-amber-800">
            <li>Comply with a legal obligation</li>
            <li>Protect and defend the rights or property of the Company</li>
            <li>Prevent or investigate possible wrongdoing in connection with the Service</li>
            <li>Protect the personal safety of Users of the Service or the public</li>
            <li>Protect against legal liability</li>
          </ul>
        </section>

        <section className="space-y-4">
          <h3 className="text-2xl font-semibold text-amber-900">Security of Your Personal Data</h3>
          <p className="text-amber-800 leading-relaxed">The security of Your Personal Data is important to Us, but remember that no method of transmission over the Internet, or method of electronic storage is 100% secure...</p>
        </section>

        <section className="space-y-4">
          <h2 className="text-3xl font-bold text-amber-900">Children's Privacy</h2>
          <p className="text-amber-800 leading-relaxed">Our Service does not address anyone under the age of 16...</p>
        </section>

        <section className="space-y-4">
          <h2 className="text-3xl font-bold text-amber-900">Links to Other Websites</h2>
          <p className="text-amber-800 leading-relaxed">Our Service may contain links to other websites that are not operated by Us...</p>
          <p className="text-amber-800 leading-relaxed">We have no control over and assume no responsibility for the content, privacy policies or practices of any third party sites or services.</p>
        </section>

        <section className="space-y-4">
          <h2 className="text-3xl font-bold text-amber-900">Changes to this Privacy Policy</h2>
          <p className="text-amber-800 leading-relaxed">We may update Our Privacy Policy from time to time. We will notify You of any changes by posting the new Privacy Policy on this page.</p>
          <p className="text-amber-800 leading-relaxed">We will let You know via email and/or a prominent notice on Our Service, prior to the change becoming effective and update the "Last updated" date at the top of this Privacy Policy.</p>
          <p className="text-amber-800 leading-relaxed">You are advised to review this Privacy Policy periodically for any changes. Changes to this Privacy Policy are effective when they are posted on this page.</p>
        </section>

        <section className="space-y-4">
          <h2 className="text-3xl font-bold text-amber-900">Contact Us</h2>
          <p className="text-amber-800 leading-relaxed">If you have any questions about this Privacy Policy, You can contact us:</p>
          <ul className="list-disc space-y-2 pl-6 text-amber-800">
            <li>By email: connect@agentsforgex.com</li>
            <li>
              By visiting this page on our website:{' '}
              <a
                href="https://agentsforgex.com"
                rel="external nofollow noopener"
                target="_blank"
                className="text-amber-900 underline hover:text-amber-700">
                https://agentsforgex.com
              </a>
            </li>
            <li>By phone: +1 (415) 831-2654</li>
          </ul>
        </section>
      </main>

      {/* FOOTER */}
      <footer className="bg-[#00332a] text-slate-100 py-16 px-6">
        <div className="max-w-7xl mx-auto grid items-start grid-cols-1 md:grid-cols-4 gap-6 mb-12">
          <div className="space-y-5">
            <img src={logoSvg} alt="AgentsForgeX" className="h-20 w-auto -mt-6 self-start" />
            <p className="text-slate-300 text-sm leading-7">
              Orchestrates autonomous AI agents into unified enterprise systems, transforming fragmented workflows into coordinated, self-executing intelligence at scale.
            </p>
          </div>

          <div className="space-y-5 self-start">
            <h4 className="font-semibold text-slate-100 mb-4">Platform</h4>
            <ul className="space-y-3 text-sm text-slate-300/80">
              <li>
                <a href="/#command-center" className="hover:text-white transition-colors">
                  Orchestration Engine
                </a>
              </li>
              <li>
                <a href="/#enterprise-scale" className="hover:text-white transition-colors">
                  Integrations
                </a>
              </li>
              <li>
                <a href="/#pricing" className="hover:text-white transition-colors">
                  Pricing
                </a>
              </li>
            </ul>
          </div>

          <div className="space-y-5 self-start">
            <h4 className="font-semibold text-slate-100 mb-4">Company</h4>
            <ul className="space-y-3 text-sm text-slate-300/80">
              <li>
                <a href="/about" className="hover:text-white transition-colors">
                  About Us
                </a>
              </li>
              <li>
                <a href="#contact" className="hover:text-white transition-colors">
                  Contact
                </a>
              </li>
              <li>
                <a href="/privacy" className="hover:text-white transition-colors">
                  Privacy Policy
                </a>
              </li>
              <li>
                <a href="/terms" className="hover:text-white transition-colors">
                  Terms of Service
                </a>
              </li>
            </ul>
          </div>

          <div className="space-y-5 self-start">
            <h4 className="font-semibold text-slate-100 mb-4">Social</h4>
            <p className="text-sm text-slate-300/80">Follow us for the latest product updates and announcements.</p>
            <div className="flex flex-wrap gap-3">
              <a href="https://www.linkedin.com/company/agentsforge-x/" target="_blank" rel="noopener noreferrer" className="inline-flex h-10 w-10 items-center justify-center rounded-full bg-white/10 text-slate-100 hover:bg-white/20 transition">
                <Linkedin className="h-5 w-5" />
                <span className="sr-only">LinkedIn</span>
              </a>
              <a href="https://x.com/AgentsForgeX" target="_blank" rel="noopener noreferrer" className="inline-flex h-10 w-10 items-center justify-center rounded-full bg-white/10 text-slate-100 hover:bg-white/20 transition">
                <X className="h-5 w-5" />
                <span className="sr-only">X</span>
              </a>
              <a href="https://www.youtube.com/@AgentsForgeX" target="_blank" rel="noopener noreferrer" className="inline-flex h-10 w-10 items-center justify-center rounded-full bg-white/10 text-slate-100 hover:bg-white/20 transition">
                <Youtube className="h-5 w-5" />
                <span className="sr-only">YouTube</span>
              </a>
              <a href="https://www.facebook.com/AgentsForgex/" target="_blank" rel="noopener noreferrer" className="inline-flex h-10 w-10 items-center justify-center rounded-full bg-white/10 text-slate-100 hover:bg-white/20 transition">
                <Facebook className="h-5 w-5" />
                <span className="sr-only">Facebook</span>
              </a>
              <a href="https://www.pinterest.com/AgentsForgex/" target="_blank" rel="noopener noreferrer" className="inline-flex h-10 w-10 items-center justify-center rounded-full bg-white/10 text-slate-100 hover:bg-white/20 transition">
                <svg viewBox="0 0 24 24" className="h-5 w-5" fill="currentColor" aria-hidden="true">
                  <path d="M12 0C5.373 0 0 5.373 0 12c0 4.99 3.657 9.166 8.438 10.06-.117-.854-.223-2.167.047-3.105.243-.836 1.567-5.314 1.567-5.314s-.398-.797-.398-1.973c0-1.848 1.072-3.228 2.406-3.228 1.136 0 1.684.852 1.684 1.873 0 1.141-.726 2.847-1.102 4.43-.313 1.327.665 2.407 1.973 2.407 2.368 0 4.186-2.494 4.186-6.085 0-3.183-2.291-5.414-5.566-5.414-3.797 0-6.036 2.851-6.036 5.795 0 1.144.44 2.374.99 3.041.109.132.125.247.094.379-.103.412-.337 1.327-.383 1.51-.06.244-.197.296-.456.178-1.694-.79-2.756-3.247-2.756-5.218 0-4.247 3.087-8.147 8.903-8.147 4.672 0 8.305 3.336 8.305 7.793 0 4.654-2.932 8.408-7.003 8.408-1.366 0-2.651-.71-3.087-1.547l-.84 3.197c-.304 1.179-1.127 2.656-1.678 3.553C8.53 23.81 10.241 24 12 24c6.627 0 12-5.373 12-12S18.627 0 12 0z" />
                </svg>
                <span className="sr-only">Pinterest</span>
              </a>
            </div>
          </div>
        </div>

        <div className="max-w-7xl mx-auto border-t border-slate-800/70 pt-6 text-sm text-slate-400/80">
          <p>© 2026 AgentsForgeX Inc. All rights reserved.</p>
        </div>
      </footer>
    </div>
  );
}
